### ISSUE TITLE
シークレットキーが取得できない

### ISSUE THREAD

**Issue by aiirononeko** [aiirononeko/languageMemoApp#125]
## 背景
APIを本番環境で動かすためにはシークレットキーが必要

↓
```
docker-compose run -e EDITOR=vim web bin/rails credentials:edit
```
↓
```
Traceback (most recent call last):
	26: from bin/rails:4:in `<main>'
	25: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
	24: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	23: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
	22: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	21: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	20: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	19: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	18: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	17: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<top (required)>'
	16: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/command.rb:46:in `invoke'
	15: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/command/base.rb:69:in `perform'
	14: from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	13: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	12: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	11: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/credentials/credentials_command.rb:26:in `edit'
	10: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/command/helpers/editor.rb:26:in `catch_editing_exceptions'
	 9: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/credentials/credentials_command.rb:27:in `block in edit'
	 8: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/credentials/credentials_command.rb:50:in `change_credentials_in_system_editor'
	 7: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/encrypted_file.rb:54:in `change'
	 6: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/encrypted_configuration.rb:21:in `read'
	 5: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/encrypted_file.rb:42:in `read'
	 4: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/encrypted_file.rb:79:in `decrypt'
	 3: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/messages/rotator.rb:21:in `decrypt_and_verify'
	 2: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/message_encryptor.rb:157:in `decrypt_and_verify'
	 1: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/message_encryptor.rb:183:in `_decrypt'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/message_encryptor.rb:206:in `rescue in _decrypt': ActiveSupport::MessageEncryptor::InvalidMessage (ActiveSupport::MessageEncryptor::InvalidMessage)
```

というエラーが発生してcredentialsファイルを編集できない。

**Comment by Kanezoh** [comment]
あー、これかあ。
GCPの設定いじってるときに同じ作業しましたよ、結局めんどくさくなってcredentialsでキー管理するのやめましたけど。
credentials.yml.encを削除してから同じコマンド叩けば動くはずです。

**Comment by Kanezoh** [comment]
進捗どうですか？How is this issue going?

**Comment by aiirononeko** [comment]
何の成果も｡｡得られませんでしたぁっ!!!!

**Comment by aiirononeko** [comment]
っていうのは嘘で昨日さぼっちゃった｡
今日やります｡
